name: Deploy Storybook to GitHub Pages

on:
  push:
    branches:
      - main # Cambia esto si tu rama principal tiene otro nombre

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20 # Usa la versión de Node.js que prefieras

      # 3. Instalar dependencias
      - name: Install dependencies
        run: npm install

      # 4. Construir Storybook
      - name: Build Storybook
        run: npm run build-storybook

      # 5. Desplegar en GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_dir: ./storybook-static