name: Build & PR Preview Storybook

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build-pr-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Storybook
        run: npm run build-storybook

      - name: Deploy PR Preview
        uses: rossjrw/pr-preview-action@v1
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          preview-branch: gh-pages
          source-dir: ./storybook-static
          umbrella-dir: pr-preview
      - name: Comentar con URL de PR Preview
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: pr-preview
          message: |
            🚀 Preview: https://pallevar-me.github.io/ollie-design-system/pr-preview/pr-${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}